name = "cldflr-remix-app"
pages_build_output_dir = "./build"
compatibility_date = "2024-04-04"

[vars]
API_KEY = "DummyKey"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "SYSTEM"
id = "2ed4cf9ab1764b6f8c55a826b86f35f7"

[[kv_namespaces]]
binding = "CONVERSATION"
id = "d7b7945e076c4ddc864e75cbd2f9a5c7"
